<a href="https://colab.research.google.com/github/1ntromann/Machine-Learning/blob/main/NumPyLearn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy Learn

In [ ]:
import numpy as np

In [ ]:
array = np.array([1,2,3,4,5])

In [ ]:
print(array)
print(array.size)
print(array.shape)
type(array)

[1 2 3 4 5]
5
(5,)


numpy.ndarray

In [ ]:
mat= np.array([(2,3,4,5),(1,9,0,7)])

mat.resize(4,2)
print(mat)
print(mat.shape)
print(mat.size)

[[2 3]
 [4 5]
 [1 9]
 [0 7]]
(4, 2)
8


In [ ]:
mat0 = np.zeros((2,3))
print(mat0)

mat1=np.ones((3,4))
print(mat1)

x=np.full((3,2),4.2)
print(x)

unit=np.eye(6)
print(unit)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[4.2 4.2]
 [4.2 4.2]
 [4.2 4.2]]
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [ ]:
# random values
y=np.random.random((3,4))
print(y)
print(y.dtype)

# random integers in a range
z=np.random.randint(10,111,(4,3))
print(z)
print(z.ndim)

[[0.18793115 0.31031931 0.83927113 0.5021455 ]
 [0.7649021  0.7926252  0.0691206  0.09251209]
 [0.62415869 0.63484539 0.33745253 0.56163456]]
float64
[[ 79  10 107]
 [ 91  18  58]
 [ 12  65 105]
 [ 13  32  45]]
2


In [ ]:
# evenly spaced values
a=np.linspace(10,20,3)
print(a)

# values in arithmetic progression
b=np.arange(10,100,12)
print(b)

[10. 15. 20.]
[10 22 34 46 58 70 82 94]


list as numpy array

In [ ]:
list1=[2,8,1,12]
arr=np.asarray(list1)
print(arr)

[ 2  8  1 12]


Mathematical operations

In [ ]:
arr1=np.array([2,1,8,4])
arr2=np.array([3,8,9,0])
arr3=arr1+arr2
print(arr3)

[ 5  9 17  4]


In [ ]:
a=np.random.randint(0,45,(3,4))
b=np.random.randint(10,60,(3,4))

# for addition we can also use print(np.add(a,b)) and similarly for subtract,mulitiply, divide
print(a)
print(" ")
print(b)
print(" ")
print(a+b)
print(" ")
print(a-b)
print(" ")
print(a*b)
print(" ")
print(a/b)

[[ 9 30 23 41]
 [ 2 32 42 29]
 [14 35 34 20]]
 
[[17 45 31 43]
 [41 56 27 51]
 [59 43 39 39]]
 
[[26 75 54 84]
 [43 88 69 80]
 [73 78 73 59]]
 
[[ -8 -15  -8  -2]
 [-39 -24  15 -22]
 [-45  -8  -5 -19]]
 
[[ 153 1350  713 1763]
 [  82 1792 1134 1479]
 [ 826 1505 1326  780]]
 
[[0.52941176 0.66666667 0.74193548 0.95348837]
 [0.04878049 0.57142857 1.55555556 0.56862745]
 [0.23728814 0.81395349 0.87179487 0.51282051]]


In [ ]:
# finding transpose
a=np.random.randint(0,45,(3,4))
print(a)
print("\n")
tran=np.transpose(a)
print(tran)

[[10 34 36 14]
 [18  6 39 13]
 [23 12 42 16]]


[[10 18 23]
 [34  6 12]
 [36 39 42]
 [14 13 16]]


In [ ]:
# finding type of function
print(type(np.add))

<class 'numpy.ufunc'>
